### ISSUE TITLE
Display names and hex codes on color samples

### ISSUE THREAD

**Issue by racheledelman** [codeforamerica/honeycrisp-gem#104]
This is our current color sample section:
![image](https://user-images.githubusercontent.com/2693690/59631440-a8d1f080-90fc-11e9-83d7-3f5e188deefd.png)
Neither the hex codes nor the color names are easy to find or associate with the color squares (obviously engineers shouldn't have to be copying hex codes, but sometimes I need to grab them). Bonus: this will also quickly show whether black or white text should be used over each color.

Let's [copy MailChimp](http://ux.mailchimp.com/patterns/color) and stick that info right in the squares:  
![image](https://user-images.githubusercontent.com/2693690/59631561-fea69880-90fc-11e9-9812-f486b349226d.png)
(They also have a "click to copy hex to your clipboard" feature, which would be awesome bonus.)

**Comment by hartsick** [comment]
I love this!
