### ISSUE TITLE
Add Honeycrisp branding 

### ISSUE THREAD

**Issue by racheledelman** [codeforamerica/honeycrisp-gem#122]
- [x] Change header title to Honeycrisp Design System vX
- [x] Change page name to Honeycrisp 
- [x] Change the URL (e.g. https://cfa-styleguide.herokuapp.com -> https://honeycrisp.herokuapp.com)
- [ ] ~Change the path within a project (e.g. https://getcalfresh.org/honeycrisp/)~ (decided not to do this for now)
- [x] Rename the repo (Github sets up a redirect when a repo is renamed, so we should be okay, but projects should still update the path in the Gemfile and re-establish Git remotes soon. e.g. from cfa-styleguide-gem -> honeycrisp-gem)

**Comment by hartsick** [comment]
If we rename the repo (which I think makes sense!), we'll need to update the URLs in projects that use it. We may also want to consider renaming the gem (right now it's `cfa-styleguide`, could just be something like `honeycrisp`).
