### ISSUE TITLE
Make tab bar selected state match background color

### ISSUE THREAD

**Issue by racheledelman** [codeforamerica/honeycrisp-gem#152]
When a [tab bar](https://honeycrisp-add-progress-vpe21f.herokuapp.com/cfa/styleguide#molecules-tab_bar) tab has a class of `is-selected`,  it's background should be white, not `grey-light`.

This is to provide differentiation between the selected and unselected tabs.
![image](https://user-images.githubusercontent.com/2693690/71028310-e7536280-20c1-11ea-940c-028ab59fc5cc.png)

**Comment by bengolder** [comment]
@racheledelman the selected tab currently uses the `$background-color` variable for its background, [which by default is not white](https://github.com/codeforamerica/honeycrisp-gem/blob/master/app/assets/stylesheets/atoms/_variables.scss#L61). It looks like the styleguide template page uses a white background, which differs from the default. Should it override any background color to be white?

**Comment by racheledelman** [comment]
Hm, good point. I guess it probably should be whatever the background is, which isn't always white. The important thing is that it be differentiated from the other tabs. What if instead we gave the unselected tabs the same background color, but with a dark tint/overlay? You can do that in SASS, right?

**Comment by ash-rc** [comment]
@racheledelman I darkened the unselected tabs by 5% in this pr: https://github.com/codeforamerica/honeycrisp-gem/pull/249. Let me know if that solves the issue for this and I'll get it code reviewed!
