### ISSUE TITLE
Compile static assets into /dist directory

### ISSUE THREAD

**Issue by luigi** [codeforamerica/honeycrisp-gem#176]
Building off the proposal in https://github.com/codeforamerica/honeycrisp-gem/issues/173#issuecomment-592213363, create a `.gitignore`ed `/dist` top-level directory.

Compile (or copy, as appropriate) the design system assets to create a public distribution. The distribution step should be run via a new rake task:

`$ rake dist`

A suggested folder structure, open for modification:

```
dist/
├── css/
│   ├── honeycrisp.min.css.map
│   ├── honeycrisp.min.css
│   └── honeycrisp.css
├── js/
│   ├── honeycrisp.min.js.map
│   ├── honeycrisp.min.js
│   └── honeycrisp.js
└── scss/ (copies of each individual SCSS component)
```

The SCSS can be copied from https://github.com/codeforamerica/honeycrisp-gem/tree/master/app/assets/stylesheets, while the compiled CSS and JS will need to use Rails' asset pipeline to generate the files.

**Comment by bencalegari** [comment]
Added my our pass at this on [generate-distro](https://github.com/codeforamerica/honeycrisp-gem/tree/generate-distro). We're putting it down for the moment to work on p-ebt but it is functional at its current state. 

To create the distribution, run: `rake assets:package`

Some todo items:
- Add dist creation instructions to README
- Fix percy tests (that I need access too)
- Add test that uses the output from `dist` to confirm it works properly
