### ISSUE TITLE
Spike on improvements to Form Builder

### ISSUE THREAD

**Issue by lkogler** [codeforamerica/honeycrisp-gem#186]
The goal is to understand how best to move forward with improvements to the Form Builder. 

- What would be the level of effort / complexity that would be required to extract the GCF form builder into Honeycrisp?
- How could we create a more consistent / flexible interface for the form builder?

**Comment by hartsick** [comment]
A thing about the interface we'd like to change: require label_text and legend_text for all methods. We think we realistically won't use the Rails default fallbacks for labels, which was the motivation for making them optional.

**Comment by hartsick** [comment]
Closing in favor of https://github.com/codeforamerica/honeycrisp-gem/issues/124
