### ISSUE TITLE
question-with-follow-up doesn't quite work for checkbox lists

### ISSUE THREAD

**Issue by tgrathwell** [codeforamerica/honeycrisp-gem#219]
If you try to use `question-with-follow-up` on checkboxes, clicking a box will appropriately show whatever it has set for its `data-follow-up`, but clicking any other box will hide that, even though the follow-uppy field is still checked.

Need to change the javascript to re-evaluate *all* follow-ups when one is clicked, not just the one you clicked.

**Comment by wschaefer** [comment]
The usage on gcf is we have a set of checkboxes and the last one is 'other' - if you check 'other' we want to show a text box so you can add details. If you first check 'other' and then check another checkbox as well the text box disappears. See this commit message for context: https://github.com/codeforamerica/gcf-backend/commit/6cc96ac23aa98bedcb96ac55592e21cbf6bd14de

**Comment by lkogler** [comment]
Closed by #251
