### ISSUE TITLE
Honeycrisp compact overrides focus styles for buttons

### ISSUE THREAD

**Issue by hartsick** [codeforamerica/honeycrisp-gem#230]
The honeycrisp compact styles specify box-shadow properties that are more specific than the default focus state (which gives an orange border). Honeycrisp compact doesn't define its own focus state styles, so it means any buttons within a .honeycrisp-compact class will not style how we'd like on focus.

I imagine we might have this issue with some other states for things in honeycrisp compact; might be worth checking as part of this issue.

**Comment by hartsick** [comment]
I think we can just add in something like

```
  .button {
    &:focus {
      @include outline;
    }
  }
```

**Comment by hartsick** [comment]
I wonder if this is worth rethinking how we are declaring the honeycrisp-compact styles, since I think accidental overrides through specificity might continue to be a problem we run into.

Ben G and I talked today and I wonder if we should be creating new top-level classes with namespaces (eg `hc-button` `hc-button--small`) rather than namespacing classes (`.honeycrisp-compact .button`). Would like to give some more thought; also invite thoughts from others!

This would allow us to more interchangeably use compact and non-compact styles if we wanted, too.

**Comment by ash-rc** [comment]
@hartsick I believe the PR I opened will fix the focus issues with Honeycrisp Compact! https://github.com/codeforamerica/honeycrisp-gem/pull/238  Due to time constraints, I didn't take on a larger refactoring with it. Maybe we could open a separate issue to capture the conversation you and @bengolder had about namespacing classes for more ease of use, and close this issue out?

**Comment by ash-rc** [comment]
Immediate issue fixed in https://github.com/codeforamerica/honeycrisp-gem/pull/238, issue https://github.com/codeforamerica/honeycrisp-gem/issues/239 opened to continue the conversation about rethinking Honeycrisp Compact
