### ISSUE TITLE
master -> main

### ISSUE THREAD

**Issue by bytheway875** [codeforamerica/honeycrisp-gem#254]
A lot of code for america apps have renamed master branch to main, and it would be great to do that in honeycrisp too! 

@embarnard did it for GYR and said it was a pretty quick process. The only additional thing we'd need to keep in mind here is:

- adding documentation to the readme to explain how to retarget to main instead of master for existing contributors
- communicating out to consuming CFA apps so that they can retarget their gemfiles from `branch: master` to `branch: main` if that's how they're importing honeycrisp.

**Comment by ash-rc** [comment]
@bytheway875 I did a search through the org for `gem 'cfa-styleguide'` [search link](https://github.com/search?q=org%3Acodeforamerica+gem+%27cfa-styleguide%27&type=Code) and `gem 'honeycrisp-gem'` [search link ](https://github.com/search?q=org%3Acodeforamerica+gem+%27honeycrisp-gem%27&type=Code) and I found that only GYR ties the branch to master for the gem!

**Comment by hartsick** [comment]
Closed by https://github.com/codeforamerica/honeycrisp-gem/commit/ff5b67d5590a61797f0857caa7b63900de1e667d & repo changes
