### ISSUE TITLE
Add Percy to GYR and run it on 3 key flows: Full service intake, CTC intake, Hub usage

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/honeycrisp-gem#270]
Work is added to the [`add-percy#177084353` branch on `vita-min`](https://github.com/codeforamerica/vita-min/tree/add-percy%23177084353) and tracked in more detail in [the GYR Pivotal Tracker](https://www.pivotaltracker.com/story/show/177084353).

- [x] Successfully create a single Percy snapshot using the CLI
- [x] Add Percy to one feature spec of a full flow and create a set of snapshots - added to `new_joint_filers_spec.rb`
- [x] Add Percy to additional feature specs - added to `visit_home_page_spec.rb`
- [x] Create repo script
- [x] Add setup and run instructions to README
- [x] Merge Percy code to `main` and get baseline snapshots for `main` branch.
- [x] Reverted, I think removing the JS dependencies will [fix the `node` issue](https://cfa.slack.com/archives/C023UQY8GQ7/p1630427617030600)
- [x] Stop screenshots from being attempted on "normal" local/ci test runs
- [x] Merge [percy improvement PR](https://github.com/codeforamerica/vita-min/pull/1600)
- [x] Use Percy to review [Honeycrisp update PR](https://github.com/codeforamerica/vita-min/pull/1252)

**Comment by coltborg** [comment]
Getting baselines shots of main thoughts:

Create a repo script (`bin/run-percy-screenshots`) that runs Percy on main and then runs Percy on new branch.

**Comment by coltborg** [comment]
Wait for a review by the GYR team.

**Comment by coltborg** [comment]
GYR reviewed and merged.
