### ISSUE TITLE
Hourly wage, input is different size

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/honeycrisp-gem#271]
Small style discrepancy we encountered when upgrading SHIBA to the latest version of Honeycrisp

[Percy failures](https://percy.io/e1ec91a4/shiba/builds/11776575/changed/662483492?browser=chrome&browser_ids=14%2C16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280)

**Comment by coltborg** [comment]
Why did this happen?

`.form-width--phone` changed from `max-width: 9.5em` to `max-width: 11em`

**Comment by coltborg** [comment]
Possible solution: don't rely on `.form-width--phone` and define a class to use `9.5em` for the hourly-wage input.

Sidenote

There were no other uses of `.form-width--phone` in the app.
