### ISSUE TITLE
Fix icons

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/honeycrisp-gem#273]
Small style discrepancy we encountered when upgrading SHIBA to the latest version of Honeycrisp

[Percy failures](https://percy.io/e1ec91a4/shiba/builds/11776575/changed/662483492?browser=chrome&browser_ids=14%2C16&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280)

- [x] Arrow button is gone
- [x] intercom button icon positioning is a little different -> it looks better now
- [x] `+` icon position is slightly off -> it looks better now
- [x] `lock` icon position is slightly -> it looks better now
- [x] `->` icon position is slightly -> is `svg` instead of material icon, moved it back into it's previous place

**Comment by coltborg** [comment]
This was happening because Honeycrisp [introduced a small vertical alignment change for icons](https://github.com/codeforamerica/honeycrisp-gem/commit/8b70d43627e6093209df3625954c5d935296d228).

We kept this vertical change for Material icons and removed it for SVG icons.
