### ISSUE TITLE
Reveal: Basic usability score

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/honeycrisp-gem#277]
Have we tested a reveal in usabilty testing with any user population and what were the results?

Possible helpful approaches:
- talk to Nicole, she may have tested it recently on CTC flow.

Acceptance criteria:
- document a score of untested/tested and good/tested and issues
- document notes of your process and how you got the score, so that we can reflect on our approach to this score.

**Comment by surandesilva** [comment]
hi
