### ISSUE TITLE
Reveal: check existing guidance

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/honeycrisp-gem#278]
Have we checked existing guidance about [reveals](http://honeycrisp.herokuapp.com/cfa/styleguide#molecules-reveal) from experts in accessibility, USWDS, GOV.UK?

Acceptance criteria:

- document a score of [unchecked] / [checked and looked good] / [checked and had issues]
- document notes of your process and how you got the score, so that we can reflect on our approach to this score. Document which sources/experts you used.

**Comment by surandesilva** [comment]
**Score: Checked and Had Issues:** 

I looked for comparable UI in the USWDS, Gov.UK, and Material.io design systems and I was unable to find something that matches our reveals. The closest related component seemed to be an accordion. 

Best Practices: 
- Make the entire header selectable ✅
- Give interactive elements enough space ✅
- Code header areas in the "accordion" as buttons ❌
- Use aria-expanded on buttons to express an "accordion’s" default state ❌
- Use unique ids - (_would depend on implementation in the product_)
- The "accordion" uses javascript to set the hidden value of its content area ❌
