### ISSUE TITLE
Reveal: automated accessibility checks

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/honeycrisp-gem#279]
Have we checked whether [reveals](http://honeycrisp.herokuapp.com/cfa/styleguide#molecules-reveal) pass automated accessibility tests?

Acceptance criteria:

- document a score of [unchecked] / [checked and looked good] / [checked and had issues]
- document notes of your process and how you got the score, so that we can reflect on our approach to this score. Which automated checks were used?

**Comment by coltborg** [comment]
**Score: Checked and looked good**

🗒️ I looked through the honeycrisp repo to answer these questions:

Is there an automated accessibility test for reveal?
- Checked by the [axe-core gem](https://github.com/dequelabs/axe-core-gems) [and passes](https://github.com/codeforamerica/honeycrisp-gem/blob/main/spec/system/accessibility_spec.rb)

Is there any other specs related to reveal?
- Yes, there is now [spec coverage for simple use-cases of reveal](https://github.com/codeforamerica/honeycrisp-gem/blob/main/spec/system/accessibility_spec.rb).
