### ISSUE TITLE
Rerun Percy on GCF to verify that there are no more upgrade bugs

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/honeycrisp-gem#283]

**Comment by coltborg** [comment]
@mquadri23 and I [pushed up a commit to reference](https://github.com/codeforamerica/gcf-backend/pull/6629/commits/a813c46dc27bd38b917b276503ab9b0085252678) the new `v0.10.3` version. Waiting for tests to pass and percy to run 🍵

**Comment by coltborg** [comment]
Things [Percy found:](https://percy.io/Code-for-America/gcf-backend/builds/12006578/changed/676043607?browser=chrome&browser_ids=16%2C19&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=375&widths=375%2C1280)

- [ ] On `end_to_end_i18n/english/en-review_pages-application-gross_income`, `emoji--money-bag` is not showing
- [ ] On some pages, the title logo is not showing
- [ ] On other pages, the title logo wasn't showing in `main` 🤔, but now is showing in the PR branch
