### ISSUE TITLE
Review automated accessibility tests for all relevant components

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/honeycrisp-gem#290]
### Summary

For the components listed below, check whether there are existing automated accessibility tests and whether the
component passes those tests or has issues.

### Details

- The [database](https://airtable.com/tblqitV9vGwdutRaq/viwV4COl82NqbMoTE?blocks=hide) and [form](https://airtable.com/shrzLthzu1DBWEtYd) are one approach I thought might make this easier to document. Let me know if you have any feedback about how documentation or tracking could be easier.
- [Reveal: automated accessibility checks #279](https://github.com/codeforamerica/honeycrisp-gem/issues/279)

#### Components

_This is a preliminary list. Please feel free to add, remove, or give feedback about the inclusion of any components in this list._

- [x] [Accordion](http://honeycrisp.herokuapp.com/cfa/styleguide#molecules-accordion)
- [x] [Auto-formatted Input](http://honeycrisp.herokuapp.com/cfa/styleguide#atoms-form_elements)
- [x] Document upload button
- [x] [Follow up question](http://honeycrisp.herokuapp.com/cfa/styleguide#molecules-follow_up_question)
- [x] [Reveal](http://honeycrisp.herokuapp.com/cfa/styleguide#molecules-reveal)
- [x] [Buttons](http://honeycrisp.herokuapp.com/cfa/styleguide#atoms-buttons)
- [x] [Checkboxes](http://honeycrisp.herokuapp.com/cfa/styleguide#atoms-form_elements)
- [x] [Data table](http://honeycrisp.herokuapp.com/cfa/styleguide#molecules-data_table)
- [x] Date select
- [x] Pagination
- [x] [Progress Indicator](http://honeycrisp.herokuapp.com/cfa/styleguide#molecules-progress_indicator)
- [x] [Progress step bar](http://honeycrisp.herokuapp.com/cfa/styleguide#molecules-progress_step_bar)
- [x] Radio buttons
- [x] [Searchbar](http://honeycrisp.herokuapp.com/cfa/styleguide#molecules-searchbar)
- [x] Select
- [x] [Steps](http://honeycrisp.herokuapp.com/cfa/styleguide#organisms-steps)
- [x] [Summary table](http://honeycrisp.herokuapp.com/cfa/styleguide#molecules-summary_table)
- [x] [Tab bar](http://honeycrisp.herokuapp.com/cfa/styleguide#molecules-tab_bar)
- [x] Text input
- [x] Textarea
- [x] [Vertical steps](http://honeycrisp.herokuapp.com/cfa/styleguide#organisms-vertical_steps)

### Acceptance

This task is complete when all of the listed components have a documented result for the specific Inclusivity Score control.
You can document the result [here](https://airtable.com/tblqitV9vGwdutRaq/viwV4COl82NqbMoTE?blocks=hide) using [this form](https://airtable.com/shrzLthzu1DBWEtYd).

**Comment by coltborg** [comment]
Complete
